name: update docs.yml
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  actions: read
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: true

      - name: Install Node dependencies
        run: pnpm install
        working-directory: compilation

      - name: Install pandoc
        run: wget https://github.com/jgm/pandoc/releases/download/3.8.3/pandoc-3.8.3-1-amd64.deb && sudo dpkg -i ./pandoc-3.8.3-1-amd64.deb

      - name: Compile GitHub Pages
        run: pnpm run compile-github-pages
        working-directory: compilation

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: compilation/dist

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
